baseURL = "https://sleepiejohn.github.io/"
languageCode = "en-us"
title = "Sleepie's Blog"
theme = 'archie'
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sleepiejohn"

[params]
mode="auto"
useCDN=false
customcss=["css/custom.css"]

